version: '3.7'

services:
  taiga-back:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga
      - POSTGRES_HOST=taiga-db
      - TAIGA_SECRET_KEY=change-me-please
      - TAIGA_SITES_SCHEME=http
      - TAIGA_SITES_DOMAIN=localhost:8000
      - RABBITMQ_USER=taiga
      - RABBITMQ_PASS=taiga
      - TAIGA_EVENTS_RABBITMQ_HOST=taiga-rabbitmq
      - TAIGA_ASYNC_RABBITMQ_HOST=taiga-rabbitmq
      - DEBUG=True
    depends_on:
      - taiga-db
      - taiga-rabbitmq
    volumes:
      - ./media:/taiga-back/media

  taiga-db:
    image: postgres:12
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data

  taiga-rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=taiga
      - RABBITMQ_DEFAULT_PASS=taiga
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  taiga-db-data:
